"""
Revit Script Exporter - Generates executable Revit API scripts.

Takes matched fixture-to-room mappings and generates:
1. pyRevit Python scripts for direct execution
2. Dynamo node definitions for visual programming
3. C# Revit API code for compiled add-in integration
"""

import json
from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime


class RevitScriptExporter:
    """
    Generates Revit-executable scripts from matched fixture data.
    
    Supports three output formats:
    - pyRevit Python script (.py) - Direct execution in Revit
    - Dynamo Python node code - For visual workflow integration
    - C# add-in code - For compiled Revit plugin
    """

    def __init__(self):
        self._generated_scripts: List[str] = []
        self._fixture_data: Optional[Dict[str, Any]] = None
        self._room_mappings: Optional[List[Dict[str, Any]]] = None

    def load_data(
        self,
        fixture_data: Dict[str, Any],
        room_mappings: List[Dict[str, Any]],
    ):
        """Load fixture and room mapping data for export."""
        self._fixture_data = fixture_data
        self._room_mappings = room_mappings

    def generate_pyrevit_script(
        self,
        output_path: str,
        project_name: str = "DIALux Fixture Import",
    ) -> str:
        """
        Generate a pyRevit-compatible Python script for Revit 2024.
        
        The generated script can be placed in a pyRevit bundle folder and
        executed directly from the Revit ribbon.
        """
        script = self._build_pyrevit_script(project_name)
        Path(output_path).write_text(script, encoding="utf-8")
        self._generated_scripts.append(output_path)
        return output_path

    def generate_dynamo_python(self, output_path: str) -> str:
        """Generate a Dynamo Python node script."""
        script = self._build_dynamo_script()
        Path(output_path).write_text(script, encoding="utf-8")
        self._generated_scripts.append(output_path)
        return output_path

    def generate_csaddin(self, output_path: str) -> str:
        """Generate a C# Revit add-in source file."""
        code = self._build_cs_addin()
        Path(output_path).write_text(code, encoding="utf-8")
        self._generated_scripts.append(output_path)
        return output_path

    def generate_report(self, output_path: str) -> str:
        """Generate a placement verification report."""
        report = self._build_placement_report()
        Path(output_path).write_text(report, encoding="utf-8")
        return output_path

    # ---- Script Builders ----

    def _build_pyrevit_script(self, project_name: str) -> str:
        """Build the pyRevit Python script content."""
        fixtures_json = json.dumps(self._fixture_data, indent=4)
        mappings_json = json.dumps(self._room_mappings, indent=4)
        
        return f'''#!/usr/bin/env python3
"""
{project_name} - DIALux to Revit Fixture Distributor
Generated by Manus AI Plugin
Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

This pyRevit script reads parsed DIALux report data and automatically
places lighting fixtures into Revit rooms, matching the DIALux layout
precisely room by room.

Usage:
    1. Place this script in your pyRevit bundle:
       %AppData%/pyRevit/extensions/your_extension.extension/DIALuxDistributor.script/
    2. Run the script from the pyRevit tab in Revit
    3. The script will read the fixture data and place fixtures
"""

# -*- coding: utf-8 -*-
import sys
import os
import json
import traceback

import Autodesk.Revit.DB as DB
from Autodesk.Revit.DB import (
    Transaction, TransactionGroup, SubTransaction,
    FamilyInstance, FamilySymbol, FilteredElementCollector,
    BuiltInCategory, BuiltInParameter,
    Room, SpatialElement, ElementId,
    XYZ, Level,
)
from Autodesk.Revit.DB.Electrical import *
from Autodesk.Revit.UI import TaskDialog, TaskDialogCommonButtons, TaskDialogResult
from Autodesk.Revit.UI.Selection import ObjectType
from pyrevit import revit, forms, script

output = script.get_output()
doc = revit.doc
uidoc = revit.uidoc

# ============================================================
# EMBEDDED FIXTURE DATA (from parsed DIALux report)
# ============================================================

FIXTURE_DATA = {fixtures_json}

ROOM_MAPPINGS = {mappings_json}

# ============================================================
# CONFIGURATION
# ============================================================

CONFIG = {{
    "default_level_offset": 0.0,  # meters above floor
    "default_mounting_height": 2.5,  # meters from floor
    "create_new_families": True,  # Auto-create families if not found
    "skip_existing_fixtures": True,  # Don't place if fixture already exists
    "round_to_mm": True,  # Round coordinates to nearest mm
    "coord_system": "project",  # "project" or "shared"
}}

# ============================================================
# FIXTURE FAMILY RESOLUTION
# ============================================================

class FamilyResolver:
    """Resolves DIALux fixture names to Revit FamilySymbol elements."""
    
    def __init__(self, doc):
        self.doc = doc
        self._cache = {{}}
        self._load_all_lighting_families()
    
    def _load_all_lighting_families(self):
        """Load all lighting fixture families in the project."""
        collector = FilteredElementCollector(self.doc) \\
            .OfCategory(BuiltInCategory.OST_LightingFixtures) \\
            .OfClass(FamilyInstance)
        
        for fi in collector:
            symbol = fi.Symbol
            if symbol and symbol.Id not in self._cache:
                self._cache[symbol.Id] = {{
                    "name": symbol.Name,
                    "family": symbol.Family.Name,
                    "element": symbol,
                }}
    
    def find_family(self, fixture_name, fixture_type="recessed"):
        """Find the best matching Revit family for a fixture name."""
        fixture_name_lower = fixture_name.lower()
        
        # Try exact match first
        for sym_id, info in self._cache.items():
            if info["name"].lower() == fixture_name_lower:
                return info["element"]
            if info["family"].lower() == fixture_name_lower:
                return info["element"]
        
        # Try fuzzy match on family name
        best_match = None
        best_score = 0.0
        
        for sym_id, info in self._cache.items():
            score = self._fuzzy_score(fixture_name_lower, info["name"].lower())
            family_score = self._fuzzy_score(fixture_name_lower, info["family"].lower())
            max_score = max(score, family_score)
            
            if max_score > best_score:
                best_score = max_score
                best_match = info["element"]
        
        if best_match and best_score >= 0.5:
            return best_match
        
        # Try type-based fallback
        type_map = {{
            "recessed": "Recessed",
            "surface": "Surface",
            "pendant": "Pendant",
            "wall": "Wall",
            "track": "Track",
        }}
        type_keyword = type_map.get(fixture_type, "Recessed")
        for sym_id, info in self._cache.items():
            if type_keyword.lower() in info["name"].lower():
                return info["element"]
        
        return None
    
    def _fuzzy_score(self, s1, s2):
        """Calculate fuzzy string matching score."""
        import difflib
        return difflib.SequenceMatcher(None, s1, s2).ratio()


# ============================================================
# FIXTURE PLACEMENT ENGINE
# ============================================================

class FixturePlacer:
    """Places lighting fixtures into Revit rooms."""
    
    def __init__(self, doc, resolver):
        self.doc = doc
        self.resolver = resolver
        self.placed_count = 0
        self.skipped_count = 0
        self.error_count = 0
        self.placement_log = []
    
    def place_all(self):
        """Place all fixtures from all rooms."""
        for mapping in ROOM_MAPPINGS:
            room_element = self._get_room_element(mapping["revit_element_id"])
            if not room_element:
                output.print_line(f"WARNING: Room element {{mapping['revit_element_id']}} not found")
                self.error_count += 1
                continue
            
            room_origin = mapping.get("origin", [0.0, 0.0])
            room_center = mapping.get("room_center", [0.0, 0.0])
            
            for fixture_info in mapping.get("fixtures", []):
                self._place_fixture_in_room(
                    room_element, room_origin, fixture_info
                )
        
        return {{
            "placed": self.placed_count,
            "skipped": self.skipped_count,
            "errors": self.error_count,
            "log": self.placement_log,
        }}
    
    def _get_room_element(self, element_id):
        """Get a Revit Room element by ID."""
        try:
            elem = self.doc.GetElement(ElementId(element_id))
            if elem and isinstance(elem, Room):
                return elem
        except:
            pass
        # Search by element_id in all rooms
        rooms = FilteredElementCollector(self.doc) \\
            .OfCategory(BuiltInCategory.OST_Rooms) \\
            .OfClass(SpatialElement)
        for r in rooms:
            if r.Id.IntegerValue == element_id:
                return r
        return None
    
    def _place_fixture_in_room(self, room, origin, fixture_info):
        """Place a single fixture type in a room."""
        fixture_name = fixture_info["name"]
        quantity = fixture_info.get("quantity", 1)
        positions = fixture_info.get("positions", [])
        
        # Find the family symbol
        symbol = self.resolver.find_family(fixture_name)
        if not symbol:
            output.print_line(f"  WARNING: No Revit family found for '{{fixture_name}}'")
            self.error_count += 1
            self.placement_log.append({{
                "action": "SKIP",
                "fixture": fixture_name,
                "room": room.Name,
                "reason": "No matching Revit family",
            }})
            return
        
        # Determine insertion point
        insertion_points = self._calculate_insertion_points(
            room, origin, positions, quantity
        )
        
        # Place each fixture
        for i, point in enumerate(insertion_points):
            try:
                # Check if fixture already exists at this location
                if CONFIG["skip_existing_fixtures"]:
                    if self._fixture_exists_at(point, symbol, room):
                        self.skipped_count += 1
                        continue
                
                # Create the fixture instance
                new_fixture = self.doc.Create.NewFamilyInstance(
                    point, symbol, room
                )
                
                if new_fixture:
                    self.placed_count += 1
                    self.placement_log.append({{
                        "action": "PLACE",
                        "fixture": fixture_name,
                        "room": room.Name,
                        "position": [point.X, point.Y, point.Z],
                        "family": symbol.Family.Name,
                    }})
            except Exception as e:
                self.error_count += 1
                self.placement_log.append({{
                    "action": "ERROR",
                    "fixture": fixture_name,
                    "room": room.Name,
                    "error": str(e),
                }})
    
    def _calculate_insertion_points(self, room, origin, positions, quantity):
        """Calculate XYZ insertion points for fixtures."""
        room_location = room.Location
        if not room_location or not hasattr(room_location, 'Point'):
            return []
        
        room_point = room_location.Point
        
        if positions and len(positions) > 0:
            # Use positions from DIALux
            points = []
            for pos in positions[:quantity]:
                x = origin[0] + pos[0]
                y = origin[1] + pos[1]
                z = room_point.Z + CONFIG["default_mounting_height"]
                if CONFIG["round_to_mm"]:
                    x = round(x * 3.28084) / 3.28084  # Round to mm
                    y = round(y * 3.28084) / 3.28084
                points.append(XYZ(x, y, z))
            return points
        else:
            # Auto-generate grid layout
            return self._generate_grid_points(room, room_point, quantity)
    
    def _generate_grid_points(self, room, center, quantity):
        """Generate a grid layout for fixtures when positions are not available."""
        import math
        
        points = []
        if quantity <= 0:
            return points
        
        # Get room bounding box
        bbox = room.get_BoundingBox(self.doc.ActiveView)
        if not bbox:
            points.append(center)
            return points
        
        width = bbox.Max.X - bbox.Min.X
        depth = bbox.Max.Y - bbox.Min.Y
        area = room.Area  # in square feet (Revit internal)
        
        # Calculate grid dimensions
        rows = max(1, int(math.sqrt(quantity * width / max(depth, 0.1))))
        cols = max(1, int(math.ceil(quantity / rows)))
        
        # Generate evenly spaced points
        margin_x = width * 0.15
        margin_y = depth * 0.15
        usable_x = width - 2 * margin_x
        usable_y = depth - 2 * margin_y
        
        placed = 0
        for r in range(rows):
            for c in range(cols):
                if placed >= quantity:
                    break
                x = bbox.Min.X + margin_x + (usable_x * c / max(cols - 1, 1))
                y = bbox.Min.Y + margin_y + (usable_y * r / max(rows - 1, 1))
                z = center.Z + CONFIG["default_mounting_height"]
                points.append(XYZ(x, y, z))
                placed += 1
            if placed >= quantity:
                break
        
        return points
    
    def _fixture_exists_at(self, point, symbol, room):
        """Check if a fixture already exists near the target point."""
        tolerance = 0.5  # feet
        collector = FilteredElementCollector(self.doc) \\
            .OfCategory(BuiltInCategory.OST_LightingFixtures) \\
            .OfClass(FamilyInstance)
        
        for fi in collector:
            loc = fi.Location
            if loc and hasattr(loc, 'Point'):
                dist = loc.Point.DistanceTo(point)
                if dist < tolerance:
                    # Check if same family
                    if fi.Symbol.Id == symbol.Id:
                        return True
        return False


# ============================================================
# MAIN EXECUTION
# ============================================================

def main():
    """Main entry point for the pyRevit script."""
    output.print_line("=" * 60)
    output.print_line(f"  DIALux to Revit Fixture Distributor")
    output.print_line(f"  Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}")
    output.print_line("=" * 60)
    output.print_line("")
    
    # Verify data
    if not FIXTURE_DATA or not ROOM_MAPPINGS:
        TaskDialog.Show("DIALux Distributor", 
            "No fixture data loaded. Please parse a DIALux report first.")
        return
    
    # Summary
    summary = FIXTURE_DATA.get("summary", {{}})
    output.print_line(f"Total fixture types: {{summary.get('total_fixtures', 0)}}")
    output.print_line(f"Total quantity: {{summary.get('total_quantity', 0)}}")
    output.print_line(f"Rooms with fixtures: {{len(ROOM_MAPPINGS)}}")
    output.print_line("")
    
    # Confirmation dialog
    result = TaskDialog.Show("DIALux Fixture Import",
        f"Ready to place {{summary.get('total_quantity', 0)}} lighting fixtures "
        f"in {{len(ROOM_MAPPINGS)}} rooms.\\n\\n"
        f"Proceed with automatic placement?")
    
    if result != TaskDialogResult.Yes:
        output.print_line("Operation cancelled by user.")
        return
    
    # Initialize resolver and placer
    resolver = FamilyResolver(doc)
    placer = FixturePlacer(doc, resolver)
    
    # Execute placement in transaction
    with Transaction(doc, "DIALux Fixture Import") as t:
        t.Start()
        try:
            results = placer.place_all()
            t.Commit()
        except Exception as e:
            t.RollBack()
            output.print_line(f"FATAL ERROR: {{e}}")
            traceback.print_exc()
            return
    
    # Report results
    output.print_line("")
    output.print_line("-" * 40)
    output.print_line(f"  PLACEMENT RESULTS")
    output.print_line("-" * 40)
    output.print_line(f"  Fixtures placed:    {{results['placed']}}")
    output.print_line(f"  Fixtures skipped:   {{results['skipped']}}")
    output.print_line(f"  Errors:             {{results['errors']}}")
    output.print_line("-" * 40)
    output.print_line("")
    
    if results["log"]:
        output.print_line("  Detailed Log:")
        for entry in results["log"][:50]:  # Show first 50 entries
            action = entry["action"]
            icon = "✓" if action == "PLACE" else ("○" if action == "SKIP" else "✗")
            output.print_line(
                f"    {{icon}} {{action}}: {{entry['fixture']}} in {{entry['room']}}"
            )
    
    output.print_line("")
    output.print_line("Done! Lighting fixtures have been distributed into the model.")


# Run the script
if __name__ == "__main__":
    main()
'''

    def _build_dynamo_script(self) -> str:
        """Build the Dynamo Python node script."""
        return '''# Dynamo Python Node Script
# DIALux to Revit Fixture Distributor
# 
# INPUTS (connect from Dynamo nodes):
#   IN[0] = Fixture data (list of dicts or JSON string)
#   IN[1] = Room mappings (list of dicts or JSON string)
#   IN[2] = Revit document (optional, auto-detected)
#
# OUTPUTS:
#   OUT[0] = Results dictionary (placed, skipped, errors)

import json
import clr

# Import Revit API
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Electrical import *
from Autodesk.Revit.UI import *
from System.Collections.Generic import List

# Import Dynamo geometry
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Get Revit document
doc = __revit__.ActiveUIDocument.Document
uidoc = __revit__.ActiveUIDocument

# Parse inputs
fixture_data = json.loads(IN[0]) if isinstance(IN[0], str) else IN[0]
room_mappings = json.loads(IN[1]) if isinstance(IN[1], str) else IN[1]

# Results tracking
results = {
    "placed": 0,
    "skipped": 0,
    "errors": 0,
    "details": []
}

# Get all lighting fixture families
fixture_collector = FilteredElementCollector(doc) \\
    .OfCategory(BuiltInCategory.OST_LightingFixtures) \\
    .OfClass(FamilyInstance)

family_cache = {}
for fi in fixture_collector:
    sym = fi.Symbol
    if sym and sym.Id not in family_cache:
        family_cache[sym.Id] = sym

# Place fixtures
TransactionManager.Instance.EnsureInTransaction(doc)

for mapping in room_mappings:
    room_id = mapping.get("revit_element_id")
    origin = mapping.get("origin", [0.0, 0.0])
    
    for fixture_info in mapping.get("fixtures", []):
        name = fixture_info["name"]
        quantity = fixture_info.get("quantity", 1)
        positions = fixture_info.get("positions", [])
        
        # Find matching family
        best_symbol = None
        best_score = 0
        
        for sym_id, symbol in family_cache.items():
            score = 0
            if symbol.Name.lower() in name.lower() or name.lower() in symbol.Name.lower():
                score = 0.8
            elif symbol.Family.Name.lower() in name.lower():
                score = 0.6
            if score > best_score:
                best_score = score
                best_symbol = symbol
        
        if not best_symbol:
            results["errors"] += 1
            results["details"].append(f"Error: No family for {name}")
            continue
        
        # Place fixtures
        for pos in positions[:quantity]:
            x = origin[0] + pos[0]
            y = origin[1] + pos[1]
            z = 0  # Will be adjusted by room height
            point = XYZ(x, y, z)
            
            try:
                new_fixture = doc.Create.NewFamilyInstance(point, best_symbol, Structure.StructuralType.NonStructural)
                if new_fixture:
                    results["placed"] += 1
                    results["details"].append(f"Placed: {name} at ({x:.2f}, {y:.2f})")
            except Exception as e:
                results["errors"] += 1
                results["details"].append(f"Error placing {name}: {str(e)}")

TransactionManager.Instance.TransactionTaskDone()

OUT = results
'''

    def _build_cs_addin(self) -> str:
        """Build the C# Revit add-in code."""
        return '''// ============================================================
// DIALux to Revit Fixture Distributor - Revit Add-in
// Generated by Manus AI Plugin
// ============================================================

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.DB.Electrical;
using Autodesk.Revit.UI;
using Autodesk.Revit.UI.Selection;

namespace RevitConduitAddin
{
    /// <summary>
    /// Command to import lighting fixtures from a DIALux report
    /// into the current Revit model, room by room.
    /// </summary>
    [Transaction(TransactionMode.Manual)]
    public class DialuxFixtureImportCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, 
            ref string message, ElementSet elements)
        {
            UIDocument uiDoc = commandData.Application.ActiveUIDocument;
            Document doc = uiDoc.Document;
            
            try
            {
                // Step 1: Let user select the parsed fixture data JSON file
                var openDialog = new System.Windows.Forms.OpenFileDialog();
                openDialog.Filter = "JSON Files (*.json)|*.json|All Files (*.*)|*.*";
                openDialog.Title = "Select Parsed DIALux Fixture Data";
                
                if (openDialog.ShowDialog() != System.Windows.Forms.DialogResult.OK)
                    return Result.Cancelled;
                
                string jsonData = File.ReadAllText(openDialog.FileName);
                var fixtureData = JsonSerializer.Deserialize<FixtureImportData>(jsonData);
                
                if (fixtureData == null || fixtureData.RoomMappings == null)
                {
                    message = "Invalid fixture data file.";
                    return Result.Failed;
                }
                
                // Step 2: Verify with user
                int totalFixtures = 0;
                foreach (var mapping in fixtureData.RoomMappings)
                    foreach (var fixture in mapping.Fixtures)
                        totalFixtures += fixture.Quantity;
                
                var confirm = TaskDialog.Show("DIALux Fixture Import",
                    $"Ready to place {totalFixtures} lighting fixtures " +
                    $"in {fixtureData.RoomMappings.Count} rooms.\\n\\n" +
                    "Proceed with automatic placement?",
                    TaskDialogCommonButtons.Yes | TaskDialogCommonButtons.No);
                
                if (confirm != TaskDialogResult.Yes)
                    return Result.Cancelled;
                
                // Step 3: Resolve families and place fixtures
                var resolver = new FamilyResolver(doc);
                var placer = new FixturePlacer(doc, resolver);
                
                using (Transaction trans = new Transaction(doc, "DIALux Fixture Import"))
                {
                    trans.Start();
                    
                    var results = placer.PlaceAll(fixtureData.RoomMappings);
                    
                    trans.Commit();
                    
                    // Step 4: Report results
                    var report = new StringBuilder();
                    report.AppendLine("DIALux Fixture Import Results:");
                    report.AppendLine($"  Placed: {results.Placed}");
                    report.AppendLine($"  Skipped: {results.Skipped}");
                    report.AppendLine($"  Errors: {results.Errors}");
                    
                    TaskDialog.Show("DIALux Fixture Import - Complete",
                        report.ToString());
                }
                
                return Result.Succeeded;
            }
            catch (Exception ex)
            {
                message = ex.Message;
                return Result.Failed;
            }
        }
    }

    // ============================================================
    // Data Models
    // ============================================================

    public class FixtureImportData
    {
        public List<RoomMapping> RoomMappings { get; set; }
        public SummaryData Summary { get; set; }
    }

    public class RoomMapping
    {
        public string DialuxRoomName { get; set; }
        public string RevitRoomName { get; set; }
        public int RevitElementId { get; set; }
        public double MatchScore { get; set; }
        public List<FixtureEntry> Fixtures { get; set; }
        public double RoomArea { get; set; }
        public double[] RoomCenter { get; set; }
        public double[] Origin { get; set; }
    }

    public class FixtureEntry
    {
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public int Quantity { get; set; }
        public double[][] Positions { get; set; }
    }

    public class SummaryData
    {
        public int TotalFixtures { get; set; }
        public int TotalQuantity { get; set; }
        public Dictionary<string, int> ByType { get; set; }
        public Dictionary<string, int> ByRoom { get; set; }
    }

    public class PlacementResults
    {
        public int Placed { get; set; }
        public int Skipped { get; set; }
        public int Errors { get; set; }
        public List<string> Log { get; set; } = new List<string>();
    }

    // ============================================================
    // Family Resolver
    // ============================================================

    public class FamilyResolver
    {
        private Document _doc;
        private Dictionary<int, FamilySymbol> _cache = 
            new Dictionary<int, FamilySymbol>();

        public FamilyResolver(Document doc)
        {
            _doc = doc;
            LoadAllLightingFamilies();
        }

        private void LoadAllLightingFamilies()
        {
            var collector = new FilteredElementCollector(_doc)
                .OfCategory(BuiltInCategory.OST_LightingFixtures)
                .OfClass(typeof(FamilyInstance));

            foreach (FamilyInstance fi in collector)
            {
                FamilySymbol symbol = fi.Symbol;
                if (symbol != null && !_cache.ContainsKey(symbol.Id.IntegerValue))
                {
                    _cache[symbol.Id.IntegerValue] = symbol;
                }
            }
        }

        public FamilySymbol FindFamily(string fixtureName)
        {
            string lowerName = fixtureName.ToLower();

            // Exact match
            foreach (var kvp in _cache)
            {
                if (kvp.Value.Name.ToLower() == lowerName ||
                    kvp.Value.Family.Name.ToLower() == lowerName)
                    return kvp.Value;
            }

            // Fuzzy match
            FamilySymbol bestMatch = null;
            double bestScore = 0;

            foreach (var kvp in _cache)
            {
                double score = FuzzyScore(lowerName, kvp.Value.Name.ToLower());
                double familyScore = FuzzyScore(lowerName, kvp.Value.Family.Name.ToLower());
                double maxScore = Math.Max(score, familyScore);

                if (maxScore > bestScore)
                {
                    bestScore = maxScore;
                    bestMatch = kvp.Value;
                }
            }

            if (bestMatch != null && bestScore >= 0.5)
                return bestMatch;

            return null;
        }

        private double FuzzyScore(string s1, string s2)
        {
            int common = 0;
            int maxLen = Math.Max(s1.Length, s2.Length);
            if (maxLen == 0) return 0;

            // Simple character overlap scoring
            foreach (char c in s1)
            {
                if (s2.Contains(c)) common++;
            }

            return (double)common / maxLen;
        }
    }

    // ============================================================
    // Fixture Placer
    // ============================================================

    public class FixturePlacer
    {
        private Document _doc;
        private FamilyResolver _resolver;
        private double _mountingHeight = 2.5; // meters
        private double _tolerance = 0.5; // feet

        public FixturePlacer(Document doc, FamilyResolver resolver)
        {
            _doc = doc;
            _resolver = resolver;
        }

        public PlacementResults PlaceAll(List<RoomMapping> mappings)
        {
            var results = new PlacementResults();

            foreach (var mapping in mappings)
            {
                // Get room element
                Element roomElement = _doc.GetElement(new ElementId(mapping.RevitElementId));
                Room room = roomElement as Room;
                
                if (room == null)
                {
                    results.Errors++;
                    results.Log.Add($"Room element {mapping.RevitElementId} not found");
                    continue;
                }

                double[] origin = mapping.Origin ?? new double[] { 0, 0 };

                foreach (var fixture in mapping.Fixtures)
                {
                    FamilySymbol symbol = _resolver.FindFamily(fixture.Name);
                    if (symbol == null)
                    {
                        results.Errors++;
                        results.Log.Add($"No family found for: {fixture.Name}");
                        continue;
                    }

                    // Place each fixture
                    var positions = fixture.Positions ?? Array.Empty<double[]>();
                    int count = Math.Min(fixture.Quantity, positions.Length);

                    if (count == 0)
                    {
                        // Auto-generate positions
                        positions = GenerateGridPositions(room, fixture.Quantity);
                        count = fixture.Quantity;
                    }

                    for (int i = 0; i < count; i++)
                    {
                        double x = origin[0] + positions[i][0];
                        double y = origin[1] + positions[i][1];
                        double z = _mountingHeight;

                        XYZ point = new XYZ(x, y, z);

                        if (FixtureExistsAt(point, symbol))
                        {
                            results.Skipped++;
                            continue;
                        }

                        try
                        {
                            FamilyInstance newFixture = _doc.Create
                                .NewFamilyInstance(point, symbol, room);
                            
                            if (newFixture != null)
                            {
                                results.Placed++;
                                results.Log.Add(
                                    $"Placed: {fixture.Name} at ({x:F2}, {y:F2}, {z:F2})");
                            }
                        }
                        catch (Exception ex)
                        {
                            results.Errors++;
                            results.Log.Add($"Error placing {fixture.Name}: {ex.Message}");
                        }
                    }
                }
            }

            return results;
        }

        private double[][] GenerateGridPositions(Room room, int quantity)
        {
            if (quantity <= 0) return Array.Empty<double[]>();

            var bbox = room.get_BoundingBox(null);
            if (bbox == null)
            {
                return new double[][] { new double[] { 0, 0 } };
            }

            double width = bbox.Max.X - bbox.Min.X;
            double depth = bbox.Max.Y - bbox.Min.Y;

            int rows = (int)Math.Sqrt(quantity * width / Math.Max(depth, 0.1));
            int cols = (int)Math.Ceiling((double)quantity / rows);

            double marginX = width * 0.15;
            double marginY = depth * 0.15;
            double usableX = width - 2 * marginX;
            double usableY = depth - 2 * marginY;

            var positions = new List<double[]>();
            int placed = 0;

            for (int r = 0; r < rows && placed < quantity; r++)
            {
                for (int c = 0; c < cols && placed < quantity; c++)
                {
                    double x = bbox.Min.X + marginX + 
                               (usableX * c / Math.Max(cols - 1, 1));
                    double y = bbox.Min.Y + marginY + 
                               (usableY * r / Math.Max(rows - 1, 1));
                    positions.Add(new double[] { x, y });
                    placed++;
                }
            }

            return positions.ToArray();
        }

        private bool FixtureExistsAt(XYZ point, FamilySymbol symbol)
        {
            var collector = new FilteredElementCollector(_doc)
                .OfCategory(BuiltInCategory.OST_LightingFixtures)
                .OfClass(typeof(FamilyInstance));

            foreach (FamilyInstance fi in collector)
            {
                LocationPoint loc = fi.Location as LocationPoint;
                if (loc != null)
                {
                    double dist = loc.Point.DistanceTo(point);
                    if (dist < _tolerance && fi.Symbol.Id == symbol.Id)
                        return true;
                }
            }
            return false;
        }
    }
}
'''

    def _build_placement_report(self) -> str:
        """Build a placement verification report in Markdown."""
        fixtures = self._fixture_data.get("fixtures", []) if self._fixture_data else []
        mappings = self._room_mappings or []
        
        report = f"""# DIALux to Revit Fixture Import Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## Project Summary

| Metric | Value |
|--------|-------|
| Total fixture types | {len(fixtures)} |
| Total quantity | {sum(f.get("quantity", 0) for f in fixtures)} |
| Rooms matched | {len(mappings)} |
| Project | {self._fixture_data.get("project_info", {}).get("project_name", "N/A") if self._fixture_data else "N/A"} |

---

## Room-by-Room Placement Plan

"""
        for mapping in mappings:
            room_name = mapping.get("revit_room_name", mapping.get("dialux_room_name", "Unknown"))
            match_score = mapping.get("match_score", 0)
            fixtures_list = mapping.get("fixtures", [])
            
            report += f"### {room_name}\n"
            report += f"- **Match Score:** {match_score:.1%}\n"
            report += f"- **Room Area:** {mapping.get('room_area', 0):.1f} sq ft\n"
            
            if fixtures_list:
                report += "\n| Fixture | Manufacturer | Quantity | Positions |\n"
                report += "|---------|-------------|----------|----------|\n"
                for f in fixtures_list:
                    pos_count = len(f.get("positions", []))
                    report += (
                        f"| {f['name']} | {f.get('manufacturer', 'N/A')} "
                        f"| {f.get('quantity', 1)} | {pos_count} coords |\n"
                    )
            else:
                report += "- No fixtures assigned\n"
            
            report += "\n"

        report += """---

## Fixture Type Summary

| Type | Count |
|------|-------|
"""
        type_counts = {}
        for f in fixtures:
            ft = f.get("fixture_type", "unknown")
            type_counts[ft] = type_counts.get(ft, 0) + f.get("quantity", 0)
        
        for ft, count in sorted(type_counts.items()):
            report += f"| {ft} | {count} |\n"

        report += f"""

---

## Notes

- Fixtures are placed at ceiling-mounted height by default (2.5m from floor)
- If DIALux positions are not available, a grid layout is auto-generated
- Existing fixtures within 0.5 ft tolerance are skipped
- Coordinates are rounded to nearest millimeter
- All placements occur within a single Revit transaction

---

*Report generated by Manus AI - DIALux to Revit Fixture Distributor*
"""
        return report
